-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgKNqqtoEcOTOhMTI2
pDnMP6E9glAfz/Iy1z6/ldPUAsigCgYIKoZIzj0DAQehRANCAAS2UFq8xelKbAS8
ZVy1e0xzMBKoB5gCDK0IYftDxRweeUbF828Da4GBVqM8YYohtSlzHEGMfgFbzu9h
zdMeFijW
-----END PRIVATE KEY-----